"""Production asset generation utilities for AutoDev Crew.

AutoDev Crew adds deployment-readiness to every generated project run. The assets
created here are deterministic templates that wrap the generated Python module,
Gradio app, and tests with Docker, CI, environment, and deployment guidance.
"""

from __future__ import annotations

import json
import os
import platform
import zipfile
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.strip() + "\n", encoding="utf-8")


def _safe_name(value: str, fallback: str = "generated-project") -> str:
    value = value.strip().lower().replace("_", "-")
    cleaned = "".join(ch if ch.isalnum() or ch == "-" else "-" for ch in value)
    cleaned = "-".join(part for part in cleaned.split("-") if part)
    return cleaned or fallback


def _dockerfile(inputs: Dict[str, Any]) -> str:
    app_file = inputs.get("app_file", "app.py")
    return f"""
# Auto-generated by AutoDev Crew
FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \\
    PYTHONUNBUFFERED=1 \\
    GRADIO_SERVER_NAME=0.0.0.0 \\
    GRADIO_SERVER_PORT=7860

WORKDIR /app

RUN apt-get update \\
    && apt-get install -y --no-install-recommends build-essential curl \\
    && rm -rf /var/lib/apt/lists/*

COPY requirements.generated.txt ./requirements.generated.txt
RUN pip install --no-cache-dir -r requirements.generated.txt

COPY . .

EXPOSE 7860

HEALTHCHECK --interval=30s --timeout=10s --start-period=20s --retries=3 \\
    CMD python -c "import urllib.request; urllib.request.urlopen('http://127.0.0.1:7860', timeout=5)" || exit 1

CMD ["python", "{app_file}"]
"""


def _docker_compose(inputs: Dict[str, Any]) -> str:
    service_name = _safe_name(inputs.get("project_slug", "autodev-generated-project"))
    return f"""
# Auto-generated by AutoDev Crew
services:
  {service_name}:
    build: .
    container_name: {service_name}
    ports:
      - "7860:7860"
    env_file:
      - .env.example
    restart: unless-stopped
"""


def _dockerignore() -> str:
    return """
__pycache__/
*.py[cod]
*.pyo
*.pyd
.Python
.env
.venv/
venv/
env/
.git/
.gitignore
.pytest_cache/
.mypy_cache/
.ruff_cache/
.DS_Store
*.log
*.zip
validation_test_stdout.log
validation_test_stderr.log
repair_attempt_*_response.txt
"""


def _requirements_generated() -> str:
    return """
gradio>=5.22.0
python-dotenv>=1.0.1
pandas>=2.0.0
"""


def _env_example(inputs: Dict[str, Any]) -> str:
    return f"""
# Generated project runtime environment
# This generated app is designed to run locally without requiring an LLM API key.
# Keep secrets out of Git. Copy this file to .env only when needed.

APP_NAME={inputs.get('project_slug', 'autodev_generated_project')}
GRADIO_SERVER_NAME=0.0.0.0
GRADIO_SERVER_PORT=7860
"""


def _github_actions(inputs: Dict[str, Any]) -> str:
    test_file = inputs.get("test_file", "test_generated_app.py")
    return f"""
name: Generated Project CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.generated.txt

      - name: Run unit tests
        run: |
          python -m unittest {test_file}

      - name: Build Docker image
        run: |
          docker build -t autodev-generated-project:ci .
"""


def _deployment_guide(inputs: Dict[str, Any]) -> str:
    project_name = inputs.get("project_name", "Generated Project")
    return f"""
# Deployment Guide: {project_name}

This folder contains a generated Python backend module, a Gradio UI, unit tests, and production-readiness assets generated by **AutoDev Crew**.

## Files Added in AutoDev Crew

| File | Purpose |
|---|---|
| `Dockerfile` | Container image for the generated Gradio app. |
| `docker-compose.yml` | One-command local container run. |
| `.dockerignore` | Keeps unnecessary files out of the Docker build context. |
| `requirements.generated.txt` | Runtime dependencies for the generated app. |
| `.env.example` | Safe environment template. |
| `.github/workflows/generated-project-ci.yml` | CI workflow for testing and Docker build. |
| `DEPLOYMENT.md` | This deployment guide. |
| `production_manifest.json` | Machine-readable production metadata. |

## Run Locally

```bash
python -m pip install -r requirements.generated.txt
python {inputs.get('app_file', 'app.py')}
```

Then open the local Gradio URL printed in the terminal.

## Run Tests

```bash
python -m unittest {inputs.get('test_file', 'test_generated_app.py')}
```

## Run with Docker

```bash
docker build -t autodev-generated-project .
docker run --rm -p 7860:7860 autodev-generated-project
```

## Run with Docker Compose

```bash
docker compose up --build
```

Then open:

```text
http://localhost:7860
```

## GitHub Actions

The generated CI workflow performs three checks:

1. installs Python dependencies,
2. runs generated unit tests,
3. builds the Docker image.

Before using it, copy the generated project files into a GitHub repository and push to `main` or `master`.

## Production Notes

- This generated project is an MVP artifact and should be reviewed before real deployment.
- Add authentication, persistence, observability, and rate limiting if exposing externally.
- Never commit real `.env` files or secrets.
- Review `05_security_review.md` before deployment.
- Review `06_validation_report.md` to confirm syntax and tests passed.
"""


def _production_manifest(inputs: Dict[str, Any], generated_files: List[str]) -> str:
    payload = {
        "project_name": inputs.get("project_name"),
        "project_slug": inputs.get("project_slug"),
        "run_id": inputs.get("run_id"),
        "workflow_version": "1.0.0",
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "python_version": platform.python_version(),
        "platform": platform.platform(),
        "frontend_framework": "Gradio",
        "llm_model": "openai/gpt-4o",
        "deployment_assets": [
            "Dockerfile",
            "docker-compose.yml",
            ".dockerignore",
            "requirements.generated.txt",
            ".env.example",
            ".github/workflows/generated-project-ci.yml",
            "DEPLOYMENT.md",
            "production_manifest.json",
        ],
        "generated_project_files": generated_files,
        "recommended_local_commands": [
            "python -m pip install -r requirements.generated.txt",
            f"python {inputs.get('app_file', 'app.py')}",
            f"python -m unittest {inputs.get('test_file', 'test_generated_app.py')}",
            "docker compose up --build",
        ],
    }
    return json.dumps(payload, indent=2, ensure_ascii=False)


def create_run_zip(run_dir: Path) -> Path:
    """Create or refresh a ZIP archive for one generated run folder."""
    zip_path = run_dir.with_suffix(".zip")
    if zip_path.exists():
        zip_path.unlink()
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for file_path in sorted(run_dir.rglob("*")):
            if file_path.is_file():
                archive.write(file_path, arcname=file_path.relative_to(run_dir.parent))
    return zip_path


def generate_deployment_assets(inputs: Dict[str, Any]) -> Dict[str, Any]:
    """Generate deployment and CI/CD assets inside a run output folder."""
    run_dir = Path(inputs["run_output_dir"])
    run_dir.mkdir(parents=True, exist_ok=True)

    assets = {
        "Dockerfile": _dockerfile(inputs),
        "docker-compose.yml": _docker_compose(inputs),
        ".dockerignore": _dockerignore(),
        "requirements.generated.txt": _requirements_generated(),
        ".env.example": _env_example(inputs),
        ".github/workflows/generated-project-ci.yml": _github_actions(inputs),
        "DEPLOYMENT.md": _deployment_guide(inputs),
    }

    for relative_name, content in assets.items():
        _write_text(run_dir / relative_name, content)

    generated_files = [str(path.relative_to(run_dir)) for path in sorted(run_dir.rglob("*")) if path.is_file()]
    _write_text(run_dir / "production_manifest.json", _production_manifest(inputs, generated_files))
    generated_files = [str(path.relative_to(run_dir)) for path in sorted(run_dir.rglob("*")) if path.is_file()]
    zip_path = create_run_zip(run_dir)

    return {
        "deployment_assets_generated": True,
        "deployment_assets_completed_at": datetime.now().isoformat(timespec="seconds"),
        "deployment_assets": sorted(assets.keys()) + ["production_manifest.json"],
        "download_zip": str(zip_path),
        "generated_file_count": len(generated_files),
    }
